### PR TITLE
Completed Lectures 22 and 23 and completed HW9

### PR DESCRIPTION
**Pull request by smitwi05**

### CODE REVIEW

**Comment by stevertaylor** [comment]
Looks like there is a conflict with hw8, @smitwi05 . Could this be because you didn't pull my marked-up version of your hw8?

**Comment by smitwi05** [comment]
You are correct, I didn't pull hw8 before submitting (sorry about that...). If I pull hw8 now after I made this request, will that fix it, break things, or neither? Let me know what I can to do on my end to fix it.

**Comment by stevertaylor** [comment]
I think if you pull the upstream changes you should be fine. Worst case scenario you can just revert to a previous version (thank you version control!).

**Comment by smitwi05** [comment]
I did the pull and it looks like there are no merger conflicts on my end. And it looks like you merged it as I was writing this.

**Pull request merged**
