### PR TITLE
hw 4

### PR DESCRIPTION
**Pull request by kekeivory**
hw 4 is completed in the most recent commit

### CODE REVIEW

**Comment by stevertaylor** [comment]
Hi @kekeivory. Thanks for this.  Could you please remove your directory "my_ptmcmc_chain" from the commit? Otherwise that large directory will be unnecessarily added to the repo here.

**Comment by kekeivory** [comment]
I *think* I fixed it!

**Comment by stevertaylor** [comment]
Almost! The PR now has conflicts with other student folders. Perhaps only commit changes in your folder?

**Comment by stevertaylor** [comment]
Hi @kekeivory , I'm still concerned about the number of files that are affected by this PR (32 files, some of which are other student's work). Crisel had a similar issue at the start of the semester so I'll connect you both to talk about solutions.

**Comment by kekeivory** [comment]
I thought I had fixed the merge issues when it finally let me commit and
merge, but I guess not. I'll see what Crisel recommends, thank you!

Le ven. 2 avr. 2021 à 5:55 PM, Stephen Taylor ***@***.***> a
écrit :

**Pull request closed without merging**
