### PR TITLE
Week 2 - Lectures 3 and 4 

### PR DESCRIPTION
**Pull request by criselsuarez**
I deleted some files from my commit so I am hoping there will be no merging problems.

### CODE REVIEW

**Comment by stevertaylor** [comment]
Hi @criselsuarez . Many of these commits will delete the other student folders and one of my base notebooks.

**Comment by criselsuarez** [comment]
Is there a way to pull from your base notebook and merge it with mine? I tried `git fetch upstream` ,  ` git checkout main`, and git `merge upstream/main` and the terminal says `Everything up-to-date`

**Comment by stevertaylor** [comment]
One extreme option would be to copy your worked Lecture_3 and Lecture_4 notebooks out of the repo folder. Then reset your fork to match the current main branch here. You can then move your lecture 3 and 4 notebooks back into your student folder, then git add just those two notebooks, do a git commit -m "..." then git push. It's extreme but I think it should work. Do you want to try it?

**Comment by criselsuarez** [comment]
I think I fixed the files? .... I went back to a previous commit when I merged and readded my updated student folder.

**Comment by stevertaylor** [comment]
@criselsuarez , this looks like it will still delete all the other student folders. If you look at the Files Changed option in this PR then you can see everything that is being altered, which includes the other student folders. I'll obviously still accept and review the notebooks. Try to fix this again, and if there are still problems then we could Zoom on Tuesday morning or before class.

**Comment by criselsuarez** [comment]
Hi @stevertaylor, I tried deleting the changed files, but I think it will still change your main repo. I can meet tomorrow at 11 or before class to look over the pull request. Thanks

**Comment by stevertaylor** [comment]
Hi @criselsuarez , ok let's meet up at 11am CT. I'll send a zoom link on Slack. Shouldn't take too long to resolve this.

**Pull request closed without merging**
